// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyCBiBjGN7vXCjqm_fSoAKCCXl5La5XqFqc',
  //   appId: '1:386506518321:web:61cdc0f0c7f7117d0b0a10',
  //   messagingSenderId: '386506518321',
  //   projectId: 'loviser-6ef34',
  //   authDomain: 'loviser-6ef34.firebaseapp.com',
  //   storageBucket: 'loviser-6ef34.appspot.com',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCd71uHtTqskz4kJCPVvCnoX_XvrDi630',
    appId: '1:236513886757:android:464946641eb50ff9a435cc',
    messagingSenderId: '236513886757',
    projectId: 'loviser-d7c8e',
    storageBucket: 'loviser-d7c8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNwbFPPDrNmqyn695ucnRDRDAnxUuOStA',
    appId: '1:236513886757:ios:b2514d0c360776c6a435cc',
    messagingSenderId: '236513886757',
    projectId: 'loviser-d7c8e',
    storageBucket: 'loviser-d7c8e.appspot.com',
    // iosClientId:
    //     '386506518321-moac1a0p6m3o00ji29op7u9j4qof4glf.apps.googleusercontent.com',
    iosBundleId: 'com.novauni.loviser',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyAAnfFQA0HYJLf-gOzL1OxAmE10evUcYlc',
  //   appId: '1:386506518321:ios:8d9242b4c111a2fb0b0a10',
  //   messagingSenderId: '386506518321',
  //   projectId: 'loviser-6ef34',
  //   storageBucket: 'loviser-6ef34.appspot.com',
  //   iosClientId:
  //       '386506518321-t75eft526u524bqduhu5qe8g0h6i9u13.apps.googleusercontent.com',
  //   iosBundleId: 'com.novauni.loviser',
  // );
}
